### ISSUE TITLE
Listado de usuarios

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-backoffice#27]
**Como** administrador del BackOffice
**Quiero** poder visualizar un listado de todos los usuarios registrados
**Para** poder visualizar la información de perfil de los mismos

**Criterios de aceptación:**
* Al acceder a la pagina de listado de usuarios debo poder visualizar un listado de los usuarios registrados en el sistema, en forma de tabla, mostrando los campos:
    * mail
    * nombre y apellido
    * fecha de creación de la cuenta
    * fecha de ultimo ingreso
    * cantidad de reportes realizados.
    * Estado (Activo/Bloqueado)

- Los usuarios están ordenados por fecha de creación de la cuenta, descendiente (último usuario creado primero)

**Comment by Santiago-Pinto** [comment]
30m invertidos en armado de endpoint y en darle un formato minimo a la tabla

**Comment by MatiasReimondo** [comment]
1h invertida en el desarrollo de backend

**Comment by Santiago-Pinto** [comment]
45m invertidos en modificar los campos de la tabla de usuarios y ordenarlos por fecha de registro

15 minutos invertidos en refactor del componente de la tabla de usuarios para modularizar mejor
