### ISSUE TITLE
Detalle incidencia

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-backoffice#29]
**Como** usuario del Backoffice
**Quiero** poder visualizar los detalles de una incidencia en especifico
**Para** poder visualizar detalles de la misma como: comentarios, imágenes, votos

**Criterios de aceptación:**
El usuario puede hacer click en el titulo de un elemento de la tabla de vista de incidencias, y acceder a una pantalla con:
- Imágenes de la incidencia, expandidas
- Si no hay imágenes se muestra un placeholder (iconito de cámara tachada)
- Título
- Mapa.
-Categoría
- Descripción Fechas de publicación, actualización, cierre. Si alguno de estos campos no estuviera definido se completara con 'N/A'

Los comentarios y votos quedan fuera de alcance en esta historia, se encaran en otras historias épicas

**Comment by Azowyl** [comment]
30m

**Comment by Azowyl** [comment]
![Desktop - 1](https://user-images.githubusercontent.com/26676533/97089369-98ddf100-160d-11eb-878b-9885600e855a.png)

**Comment by Santiago-Pinto** [comment]
16h 28m destinadas al layout, estilos e investigacion de herramientas para armar el detalle de la incidencia
