### ISSUE TITLE
Login a backoffice

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#51]
**Como** administrador del backoffice
**Quiero** poder ingresar al sistema con credenciales de usuario + contraseña
**Para** poder administrar la aplicación

**Criterios de aceptación**
- La primera pantalla que ve un usuario que aún no ingresó al sistema es un formulario de login con dos campos: email + contraseña, y un botón "Ingresar".
- No hay registro, las credenciales de usuarios admin deben ser provistas de manera segura por fuera del sistema
- Si el usuario ingresa credenciales correctas se lo redirige a la home de la aplicación y se lo considera como autenticado correctamente
- Si el usuario ingresa credenciales incorrectas, se le muestra un mensaje "Usuario o contraseña incorrectos."
- Si el usuario no está autenticado correctamente, al intentar ingresar a cualquier otra vista de la aplicación, deberá ser redirigido a la primer pantalla de login.

- La creación de usuarios la hacemos desde el backend, y la contraseña debe cumplir reglas de seguridad (longitud mínima, mayusculas, minusculas, numeros, ...)

-La contraseña debe contener de 8 a 20 caracteres
- Al menos una mayuscula
- Al menos una minuscula
- Al menos un numero
-Al menos un caracter especial
- No debe contener espacios en blanco

![WhatsApp Image 2020-11-07 at 18 25 42](https://user-images.githubusercontent.com/26676533/98603433-c9d24d00-22c0-11eb-99c2-0c847bf9f594.jpeg)

**Comment by Santiago-Pinto** [comment]
![image](https://user-images.githubusercontent.com/28553568/98603609-1b7ad780-22c1-11eb-8661-c813182ad3df.png)

**Comment by Santiago-Pinto** [comment]
13h 36m invertidos en:

- Logica de login y proteccion de rutas contra autenticacion

- Estilos de la pantalla de login

**Comment by Santiago-Pinto** [comment]
1h15m invertidos en agregar la logica de display de un cartel de error en caso de que las credenciales provistas para el login sean incorrectas
