### ISSUE TITLE
Filtros en backoffice 

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#52]
**Como** administrador del Backoffice
**Quiero** poder buscar los distintos reportes siguiendo ciertos filtros
**Para** poder encontrarlos mas rápidamente

**Criterios de aceptación:**
- Se puede filtrar por zona (barrio)
- Se puede filtrar por categoría del incidente
- Se pueden seleccionar múltiples opciones por cada tipo de filtro, es decir se puede filtrar por múltiples barrios + múltiples incidencias todo a la vez. Los filtros del mismo tipo son un OR lógico (filtro por incidencias que estén en San Telmo o Palermo), y de distintos tipos es un AND lógico (filtro por incidencias de categoría Inseguridad y barrio San Telmo).
- Al hacer click en un filtro, automáticamente se actualiza la tabla con las incidencias que cumplen ese filtros.
- Al hacer click en "Limpiar Filtros" se desactivan todos los filtros y se muestra la lista de incidencias original, con las incidencias más recientes

![image](https://user-images.githubusercontent.com/19612265/98577717-1d31a480-229b-11eb-9e92-c302e8b71376.png)

**Comment by Santiago-Pinto** [comment]
8h33m Invertidos en investigar librerias de filtros, implementacion y logica de uso
