### ISSUE TITLE
Modificaciones en las columnas de tabla de incidencia

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#53]
**Como** usuario del backoffice
**Quiero** ver mejores columnas en la tabla incidencias
**Para** ver sólo los datos que me parecen relevantes

Criterio de aceptación:
- No se puede visualizar latitud y longitud en la tabla
- No se puede visualizar más la descripción
- No se puede visualizar más las imágenes.
- Se puede ver una columna con "cantidad de votos"
- Se puede ver una columna de "Barrio"

**Comment by Santiago-Pinto** [comment]
Invertidos 10m en quitar las columnas innecesarias y en el agregado de las nuevas
