### ISSUE TITLE
Cambiar estado de reportes en backoffice

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#61]
**Como** administrador del Backoffice
**Quiero** cambiar el estado de los reportes
**Para** que reflejen el avance real de la reparación

## Criterios de aceptacion
* Existen dos botones en el detalle de incidencia, listando el estado público y el privado
* Al hacer click en uno, se abre un modal que nos permite:
  * Cambiar el estado a otro (a través de un selector)
  * Agregar un comentario interno (opcional)

* Se puede transicionar de cualquier estado a cualquier otro, no hay restricciones
* Al hacer click afuera se cierra el modal
* Al hacer click en cancelar se cierra el modal
* Cuando se confirma, se actualiza el estado y se puede visualizar en el detalle el estado nuevo
* Cuando se confirma, se actualizan los comentarios y se puede visualizar el detalle los comentarios nuevos
* Si se ingresa un comentario, se puede visualizar en el listado de comentarios internos

![image](https://user-images.githubusercontent.com/19612265/100400729-39249c80-3036-11eb-9749-2d2badcc11b4.png)
![image](https://user-images.githubusercontent.com/19612265/100400764-59ecf200-3036-11eb-9264-489fd2ac737f.png)

**Comment by Santiago-Pinto** [comment]
2h34m Invertidas en el armado del modal para el cambio de estado

**Comment by lucaslavandeira** [comment]
Invertidas 8h en retrabajo
