### ISSUE TITLE
Visualización de comentarios

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#63]
**Como** administrador del backoffice
**Quiero** poder visualizar los comentarios de una incidencia en la vista de detalle
**Para** estar al tanto de las últimas actualizaciones de la misma

## Criterios de aceptacion
* En la pantalla de detalle de incidencia, se pueden observar los comentarios realizados por usuarios sobre la incidencia en cuestion
* Cada comentario se compone de:
  * Avatar del usuario
  * Nombre del usuario
  * Comentario
  * Fecha del comentario
* No se pueden editar los comentarios
* No se pueden borrar los comentarios  

![Desktop - 2 (2)](https://user-images.githubusercontent.com/26676533/99915618-7a8a1480-2ce3-11eb-95a5-3ad3b2bcea64.png)

**Comment by Santiago-Pinto** [comment]
5h 23m invertidas en el armado del layout de la caja de comentarios asi como la logica de carga de los comentarios publicos de una incidencia

**Comment by Santiago-Pinto** [comment]
57m Invertidos en arreglar un bug de cuestiones asincronicas y agregar los comentarios privados a los comentarios que aparecen en el detalle de cada incidencia

**Comment by Santiago-Pinto** [comment]
5h invertidas en cambiar el layout de la caja de comentarios para que admita un tab que permita cambiar entre comentarios publicos y privados
