### ISSUE TITLE
Subcategorías en backoffice

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#67]
**Como** usuario de backoffice
**Quiero** poder observar la subcategoría en el detalle de la incidencia
**Para** tener más detalle de la misma

**Criterios de aceptación**
- Se ve la **subcategoría** en la tabla de listado de incidencias, bajo el nombre de "tipo"
- Se puede ver la **subcategoría** en el detalle del listado de incidencias

**Comment by Santiago-Pinto** [comment]
1H invertida en incluir la subcategoria a la tabla de incidencias y en modificar el layout del detalle de incidentes para que incluya la subcategoria del mismo

**Comment by Santiago-Pinto** [comment]
1H invertida en modificar estilos para que los labels de estado publico, privado y la subcategoria queden prolijos
