### ISSUE TITLE
Tabla complementaria del mapa de calor

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#78]
**Como** usuario administrador del backoffice
**Quiero** visualizar una tabla complementaria junto con el mapa de calor de incidencias
**Para** entender mejor qué barrios son los más afectados

**Criterios de Aceptación**:
Abajo del mapa se pueden apreciar una tabla complementaria de datos: un ranking de incidencias según barrio, ordenadas de mayor a menor (el barrio con más incidencias primero)

**Comment by Santiago-Pinto** [comment]
5h invertidas en el armado de la tabla complementaria del mapa de calor
