### ISSUE TITLE
Tabla analítica del gráfico de categorías y estados

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backoffice#79]
**Como** usuario administrador del backoffice
**Quiero** visualizar una tabla analítica junto al gráfico de Pareto de categorías y estados
**Para** entender mejor los datos presentados

**Criterios de Aceptación:**
Abajo del gráfico de Pareto se puede apreciar una tabla analítica: Los mismos datos de categoría (eje X), y estado (eje Y), con cada celda siendo la cantidad de incidencias con esa categoría y ese estado.

![image](https://user-images.githubusercontent.com/19612265/101292166-9a91fb80-37ec-11eb-9ed5-e034a6b5da73.png)

**Comment by Santiago-Pinto** [comment]
2h 50m invertidas en el armado de la tabla de estados y categorias con columnas dinamicas
